ERT:
  tables:
    eyeriss.DRAM:
      idle:
        arguments: null
        energy: 0
      read:
        arguments: null
        energy: 512
      write:
        arguments: null
        energy: 512
    eyeriss.GlobalBuffer:
      idle:
        arguments: null
        energy: 0.005
      read:
      - arguments:
          address_delta: 0
          data_delta: 0
        energy: 0.005
      - arguments:
          address_delta: 0
          data_delta: 1
        energy: 15.425
      - arguments:
          address_delta: 1
          data_delta: 0
        energy: 0.418
      - arguments:
          address_delta: 1
          data_delta: 1
        energy: 15.838
      - arguments:
          address_delta: 2
          data_delta: 0
        energy: 0.831
      - arguments:
          address_delta: 2
          data_delta: 1
        energy: 16.251
      - arguments:
          address_delta: 3
          data_delta: 0
        energy: 1.244
      - arguments:
          address_delta: 3
          data_delta: 1
        energy: 16.665
      - arguments:
          address_delta: 4
          data_delta: 0
        energy: 1.657
      - arguments:
          address_delta: 4
          data_delta: 1
        energy: 17.078
      - arguments:
          address_delta: 5
          data_delta: 0
        energy: 2.071
      - arguments:
          address_delta: 5
          data_delta: 1
        energy: 17.491
      - arguments:
          address_delta: 6
          data_delta: 0
        energy: 2.484
      - arguments:
          address_delta: 6
          data_delta: 1
        energy: 17.904
      - arguments:
          address_delta: 7
          data_delta: 0
        energy: 2.897
      - arguments:
          address_delta: 7
          data_delta: 1
        energy: 18.317
      - arguments:
          address_delta: 8
          data_delta: 0
        energy: 3.31
      - arguments:
          address_delta: 8
          data_delta: 1
        energy: 18.73
      - arguments:
          address_delta: 9
          data_delta: 0
        energy: 3.723
      - arguments:
          address_delta: 9
          data_delta: 1
        energy: 19.143
      - arguments:
          address_delta: 10
          data_delta: 0
        energy: 4.136
      - arguments:
          address_delta: 10
          data_delta: 1
        energy: 19.556
      - arguments:
          address_delta: 11
          data_delta: 0
        energy: 4.549
      - arguments:
          address_delta: 11
          data_delta: 1
        energy: 19.969
      - arguments:
          address_delta: 12
          data_delta: 0
        energy: 4.962
      - arguments:
          address_delta: 12
          data_delta: 1
        energy: 20.382
      - arguments:
          address_delta: 13
          data_delta: 0
        energy: 5.375
      - arguments:
          address_delta: 13
          data_delta: 1
        energy: 20.795
      - arguments:
          address_delta: 14
          data_delta: 0
        energy: 5.788
      - arguments:
          address_delta: 14
          data_delta: 1
        energy: 21.208
      - arguments:
          address_delta: 15
          data_delta: 0
        energy: 6.201
      - arguments:
          address_delta: 15
          data_delta: 1
        energy: 21.621
      - arguments:
          address_delta: 16
          data_delta: 0
        energy: 6.614
      - arguments:
          address_delta: 16
          data_delta: 1
        energy: 22.034
      write:
      - arguments:
          address_delta: 0
          data_delta: 0
        energy: 0.005
      - arguments:
          address_delta: 0
          data_delta: 1
        energy: 16.363
      - arguments:
          address_delta: 1
          data_delta: 0
        energy: 0.443
      - arguments:
          address_delta: 1
          data_delta: 1
        energy: 16.801
      - arguments:
          address_delta: 2
          data_delta: 0
        energy: 0.882
      - arguments:
          address_delta: 2
          data_delta: 1
        energy: 17.239
      - arguments:
          address_delta: 3
          data_delta: 0
        energy: 1.32
      - arguments:
          address_delta: 3
          data_delta: 1
        energy: 17.677
      - arguments:
          address_delta: 4
          data_delta: 0
        energy: 1.758
      - arguments:
          address_delta: 4
          data_delta: 1
        energy: 18.116
      - arguments:
          address_delta: 5
          data_delta: 0
        energy: 2.196
      - arguments:
          address_delta: 5
          data_delta: 1
        energy: 18.554
      - arguments:
          address_delta: 6
          data_delta: 0
        energy: 2.634
      - arguments:
          address_delta: 6
          data_delta: 1
        energy: 18.992
      - arguments:
          address_delta: 7
          data_delta: 0
        energy: 3.072
      - arguments:
          address_delta: 7
          data_delta: 1
        energy: 19.43
      - arguments:
          address_delta: 8
          data_delta: 0
        energy: 3.511
      - arguments:
          address_delta: 8
          data_delta: 1
        energy: 19.868
      - arguments:
          address_delta: 9
          data_delta: 0
        energy: 3.949
      - arguments:
          address_delta: 9
          data_delta: 1
        energy: 20.306
      - arguments:
          address_delta: 10
          data_delta: 0
        energy: 4.387
      - arguments:
          address_delta: 10
          data_delta: 1
        energy: 20.744
      - arguments:
          address_delta: 11
          data_delta: 0
        energy: 4.825
      - arguments:
          address_delta: 11
          data_delta: 1
        energy: 21.183
      - arguments:
          address_delta: 12
          data_delta: 0
        energy: 5.263
      - arguments:
          address_delta: 12
          data_delta: 1
        energy: 21.621
      - arguments:
          address_delta: 13
          data_delta: 0
        energy: 5.701
      - arguments:
          address_delta: 13
          data_delta: 1
        energy: 22.059
      - arguments:
          address_delta: 14
          data_delta: 0
        energy: 6.139
      - arguments:
          address_delta: 14
          data_delta: 1
        energy: 22.497
      - arguments:
          address_delta: 15
          data_delta: 0
        energy: 6.578
      - arguments:
          address_delta: 15
          data_delta: 1
        energy: 22.935
      - arguments:
          address_delta: 16
          data_delta: 0
        energy: 7.016
      - arguments:
          address_delta: 16
          data_delta: 1
        energy: 23.373
    eyeriss.PE.MACs:
      idle:
        arguments: null
        energy: 0.86
      mac_gated:
        arguments: null
        energy: 32.328
      mac_random:
        arguments: null
        energy: 32.328
      mac_reused:
        arguments: null
        energy: 32.328
    eyeriss.PE.RegFile:
      idle:
        arguments: null
        energy: 0.02
      read:
      - arguments:
          address_delta: 0
          data_delta: 0
        energy: 0.02
      - arguments:
          address_delta: 0
          data_delta: 1
        energy: 0.296
      - arguments:
          address_delta: 1
          data_delta: 0
        energy: 1.869
      - arguments:
          address_delta: 1
          data_delta: 1
        energy: 2.145
      write:
      - arguments:
          address_delta: 0
          data_delta: 0
        energy: 0.02
      - arguments:
          address_delta: 0
          data_delta: 1
        energy: 0.296
      - arguments:
          address_delta: 1
          data_delta: 0
        energy: 1.869
      - arguments:
          address_delta: 1
          data_delta: 1
        energy: 2.145
  version: 0.2
